// Command seed writes the demo's fixture records through Notary's real write
// paths: internal/ledger for the records (which is the only component that
// appends, and the only one that signs) and internal/gap for one gap entry.
//
// It exists because a shell script cannot produce *signed* records: every
// record goes through internal/ledger, which links, hashes and signs it. The
// demo script (scripts/demo.sh) therefore drives this program rather than
// hand-writing rows, so what the demo shows is what the product writes.
//
// It lives under testdata/ so that `go build ./...`, `go vet ./...` and
// `go test ./...` skip it: it is a fixture generator, not part of the module's
// shipped surface. Run it as:
//
//	go run ./testdata/demo/seed [seed|gap|tamper|pubkey]
//
// Modes (default "seed"):
//
//	seed    append the fixture records to NOTARY_DB_PATH (idempotent: a re-run
//	        appends nothing, because every record carries the content-derived
//	        idempotency key its real producer would give it)
//	gap     append the fixture gap entry to NOTARY_GAP_LOG_PATH
//	tamper  the demo's villain: rewrite one stored record's content_text by raw
//	        SQL, out of band, the way an edit to the database file would
//	pubkey  print the base64 ed25519 PUBLIC key of NOTARY_SIGNING_KEY to
//	        stdout, so the demo can write a trusted-keys file for verify/replay
//	        without ever committing key material
//
// Nothing here is a secret: the signing key is read from the environment and
// never printed. The key that seeds the demo is generated by scripts/demo.sh at
// runtime, into a temporary directory.
package main

import (
	"crypto/ed25519"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"time"

	_ "modernc.org/sqlite" // registers the "sqlite" driver for the raw-SQL tamper

	"notary/config"
	"notary/internal/gap"
	"notary/internal/ledger"
	"notary/internal/record"
	"notary/internal/sign"
	"notary/internal/store"
)

// Fixture identity. Every id, instant and key below is fixed, so the demo's
// output is the same on every run and the seeder is idempotent on the pair
// (id, idempotency key) rather than on wall-clock luck.
const (
	demoUser  = "demo-user"
	demoAgent = "demo-agent"

	// tamperRecordID is the record the tamper mode rewrites: the memory that
	// a search returned, so the demo can say "someone edited the memory text
	// that was surfaced".
	tamperRecordID = "demo-search-1#1"
	// tamperText is what that record's stored text is changed to. It is
	// deliberately a different claim, not a garbled copy: the point is that
	// verify still catches it.
	tamperText = "the beta customer prefers SMS at 2am"

	// gapCorrelationID is the id of the record the gap stands in for: a
	// record that was never written, which is exactly why the gap is
	// outstanding and why `notary gaps` reports it.
	gapCorrelationID = "demo-drop-2#lost-search"
)

// demoBase is the instant the fixtures are anchored to: the demo's "today" for
// event times. It is in the past so an `export --from` and a `replay --at`
// window are both meaningful.
var demoBase = time.Date(2026, 9, 1, 9, 0, 0, 0, time.UTC)

// The two memories the demo tells a story about, and their text. mem-demo-1 is
// kept and then re-derived by a reconciler pass; mem-demo-2 is requested and
// then dropped, so `explain --memory` has two different lifecycles to filter.
const (
	demoMemory1 = "mem-demo-1"
	demoText1   = "the beta customer prefers email updates"
	demoMemory2 = "mem-demo-2"
	demoText2   = "Dana's direct line is 555-0100"
)

func main() {
	mode := "seed"
	if len(os.Args) > 1 {
		mode = os.Args[1]
	}
	if len(os.Args) > 2 {
		fail("usage: seed [seed|gap|tamper|pubkey]")
	}

	cfg, err := config.Load()
	if err != nil {
		fail("loading configuration: %v", err)
	}

	switch mode {
	case "seed":
		err = seedRecords(cfg)
	case "gap":
		err = seedGap(cfg)
	case "tamper":
		err = tamper(cfg)
	case "pubkey":
		err = printPublicKey(cfg)
	default:
		fail("unknown mode %q: use seed, gap, tamper or pubkey", mode)
	}
	if err != nil {
		fail("%v", err)
	}
}

// fail reports a fatal error on stderr and exits 2. The program is a fixture
// generator, so it reports and exits rather than panicking.
func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "seed: "+format+"\n", args...)
	os.Exit(2)
}

// signerFromEnv builds the Signer the ledger signs with, from the variable
// config names (NOTARY_SIGNING_KEY). NewSigner never generates a key, so an
// unset or malformed variable is an error rather than a silently unsigned run.
func signerFromEnv(cfg *config.Config) (*sign.Signer, error) {
	sg, err := sign.NewSigner(sign.KeySource{Kind: sign.KeySourceEnv, Ref: cfg.SigningKeyEnv})
	if err != nil {
		return nil, fmt.Errorf("loading signing key: %w", err)
	}
	return sg, nil
}

// seedRecords appends the fixture records through the real ledger and prints
// one line per record: whether it was appended now or was already present.
//
// Idempotency is the ledger's own: every fixture carries the content-derived
// key its real producer would derive (record.DeriveIdemKey on the request path
// -- add_requested, search_performed, memory_surfaced -- and
// record.DeriveClaimIdemKey off it, for the claims a reconcile pass derives),
// so a second run against the same file appends nothing and returns the first
// run's records. The demo runs the seeder against a fresh temporary ledger, so
// in the demo's own run every line reads "appended"; the property is what makes
// running the script twice safe.
func seedRecords(cfg *config.Config) error {
	sg, err := signerFromEnv(cfg)
	if err != nil {
		return err
	}

	st, err := store.Open(cfg.DBPath)
	if err != nil {
		return fmt.Errorf("opening ledger %s: %w", cfg.DBPath, err)
	}
	defer func() { _ = st.Close() }()

	l := ledger.New(st, sg, nil)
	for _, rec := range fixtures() {
		if prior, err := l.GetRecord(rec.ID); err == nil {
			fmt.Printf("already present  %-22s seq %d\n", rec.ID, prior.Seq)
			continue
		} else if !errors.Is(err, store.ErrNotFound) {
			return fmt.Errorf("checking record %s: %w", rec.ID, err)
		}

		id, err := l.Append(rec)
		if err != nil {
			return fmt.Errorf("appending record %s: %w", rec.ID, err)
		}
		written, err := l.GetRecord(id)
		if err != nil {
			return fmt.Errorf("reading back record %s: %w", id, err)
		}
		fmt.Printf("appended         %-22s seq %d\n", id, written.Seq)
	}
	return nil
}

// seedGap appends the demo's one gap entry through the real gap log. The entry
// is deliberately UNRECONCILED: no record in the ledger carries its
// (kind, scope, correlation id), so it stays outstanding and both `notary
// gaps` and `notary verify` report it until a record accounts for it. That is
// what the demo shows -- the fail-open-loud path left a durable trace.
//
// Its Detail describes the failure and quotes no memory text: a gap entry is a
// statement about the audit trail, never a copy of the content that could not
// be audited.
func seedGap(cfg *config.Config) error {
	log, err := gap.Open(cfg.GapLogPath)
	if err != nil {
		return fmt.Errorf("opening gap log: %w", err)
	}
	defer func() { _ = log.Close() }()

	entry := gap.Entry{
		At:            demoBase.Add(2*time.Hour + 30*time.Minute),
		Kind:          record.EventMemoryDropped,
		Scope:         record.Scope{UserID: demoUser, AgentID: demoAgent},
		CorrelationID: gapCorrelationID,
		Detail:        "the ledger store rejected the append while a search was running, so this record was never written; the memory text is NOT reproduced here",
	}
	if err := log.Record(entry); err != nil {
		return fmt.Errorf("recording gap entry: %w", err)
	}
	fmt.Printf("recorded gap     %-22s kind %s\n", entry.CorrelationID, entry.Kind)
	return nil
}

// tamper rewrites one stored record's content text with raw SQL on its own
// connection -- an out-of-band edit of the database file, exactly what the
// hash chain exists to catch. It touches no chain field: the stored hash and
// signature are left as they were, which is the whole point. `notary verify`
// must name this record and the field that no longer recomputes.
func tamper(cfg *config.Config) error {
	db, err := sql.Open("sqlite", cfg.DBPath)
	if err != nil {
		return fmt.Errorf("opening %s for tampering: %w", cfg.DBPath, err)
	}
	defer func() { _ = db.Close() }()

	res, err := db.Exec(`UPDATE records SET content_text = ? WHERE id = ?`, tamperText, tamperRecordID)
	if err != nil {
		return fmt.Errorf("tampering with record %s: %w", tamperRecordID, err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("counting tampered rows: %w", err)
	}
	if n != 1 {
		return fmt.Errorf("tamper: expected to rewrite 1 row, rewrote %d (run the seed mode first)", n)
	}
	fmt.Printf("tampered         %-22s content_text := %q\n", tamperRecordID, tamperText)
	return nil
}

// printPublicKey writes the base64 ed25519 public key matching
// NOTARY_SIGNING_KEY to stdout, with a trailing newline and nothing else, so
// the demo can redirect it straight into a trusted-keys file for `notary
// verify` and `notary replay`. The private key is never printed.
//
// The key material is decoded here rather than through internal/sign because
// the package deliberately exposes no public-key accessor -- a Signer's only
// public fact is its KeyID, which is the fingerprint, not the key. The accepted
// forms are sign's: standard base64 of a 32-byte seed or a 64-byte private key.
func printPublicKey(cfg *config.Config) error {
	material, err := base64.StdEncoding.DecodeString(os.Getenv(cfg.SigningKeyEnv))
	if err != nil {
		return fmt.Errorf("key material in %s is not valid standard base64: %w", cfg.SigningKeyEnv, err)
	}

	var priv ed25519.PrivateKey
	switch len(material) {
	case ed25519.SeedSize:
		priv = ed25519.NewKeyFromSeed(material)
	case ed25519.PrivateKeySize:
		priv = make(ed25519.PrivateKey, ed25519.PrivateKeySize)
		copy(priv, material)
	default:
		return fmt.Errorf("key material in %s must decode to %d bytes (seed) or %d bytes (private key), got %d",
			cfg.SigningKeyEnv, ed25519.SeedSize, ed25519.PrivateKeySize, len(material))
	}

	pub, ok := priv.Public().(ed25519.PublicKey)
	if !ok {
		return errors.New("deriving the public key: unexpected key type")
	}
	fmt.Println(base64.StdEncoding.EncodeToString(pub))
	return nil
}

// fixtures returns the demo's records in the order they are written: one
// memory's life from the add that created it to the Reconstructed claim a
// reconciler pass derived about it months later, and a second memory that was
// requested and then dropped.
//
// Every record is built exactly as its real producer builds it -- the Observed
// records as internal/interceptor's Observer builds them (a content digest on
// the subject, the response payload as evidence, the memory text as Content),
// and the derived claims as internal/reconcile builds them (a Reconstructed
// reason resting on a named basis, rule and rule version, or an Internal note)
// -- so the demo's ledger is a faithful model of a real one, not a shape only
// the demo can produce.
//
// One deliberate fixture choice: the subject's memory id is set on ALL of the
// first memory's records, including the add and the search. A live writer
// cannot know the id yet at those two points (record.Subject documents
// MemoryID as optional for a record that precedes the memory's existence), and
// setting it is what lets a single `notary explain --memory mem-demo-1` show
// the whole arc -- add, search, surfaced, kept, and the late Reconstructed
// claim -- in one view.
func fixtures() []record.Record {
	scope1 := record.Scope{UserID: demoUser, AgentID: demoAgent}
	query := "what does the beta customer prefer?"

	hash1 := record.ContentHash(demoText1)
	hash2 := record.ContentHash(demoText2)
	queryHash := record.ContentHash(query)

	return []record.Record{
		// The request path: an add is acknowledged. The memory does not exist
		// yet, so Mem0's id comes back later (on the add_resolved record).
		observed(record.Record{
			ID:         "demo-add-1",
			At:         demoBase,
			RecordedAt: demoBase.Add(2 * time.Second),
			Event:      record.EventAddRequested,
			Subject:    record.Subject{MemoryID: demoMemory1, Scope: scope1, ContentHash: hash1},
			Content:    &record.Content{Text: demoText1},
		}, record.ReasonAddAcknowledged, `{"event_id":"demo-event-1","status":"PENDING"}`,
			idemKey(record.EventAddRequested, record.ReasonAddAcknowledged, scope1, "", "demo-add-1", hash1)),

		// The same add, resolved: a reconcile pass polled Mem0 and found the
		// memory stored. It is written minutes after the event it describes.
		observed(record.Record{
			ID:         "demo-add-1#resolved",
			At:         demoBase.Add(90 * time.Second),
			RecordedAt: demoBase.Add(5 * time.Minute),
			Event:      record.EventAddResolved,
			Subject:    record.Subject{MemoryID: demoMemory1, Scope: scope1, ContentHash: hash1},
		}, record.ReasonStoredByMem0, `{"event_id":"demo-event-1","status":"SUCCEEDED"}`,
			idemKey(record.EventAddResolved, record.ReasonStoredByMem0, scope1, "demo-event-1", "", record.Hash{})),

		// A search runs in the scope...
		observed(record.Record{
			ID:         "demo-search-1",
			At:         demoBase.Add(10 * time.Minute),
			RecordedAt: demoBase.Add(10*time.Minute + time.Second),
			Event:      record.EventSearchPerformed,
			Subject:    record.Subject{MemoryID: demoMemory1, Scope: scope1, ContentHash: queryHash},
		}, record.ReasonSearchPerformed,
			`{"query":"what does the beta customer prefer?","top_k":5,"threshold":0.3,"count":1}`,
			idemKey(record.EventSearchPerformed, record.ReasonSearchPerformed, scope1, "", "demo-search-1", queryHash)),

		// ...and returns one memory, which is where its text is recorded. This
		// is the record the demo's tamper mode later rewrites.
		observed(record.Record{
			ID:         "demo-search-1#1",
			At:         demoBase.Add(10 * time.Minute),
			RecordedAt: demoBase.Add(10*time.Minute + time.Second),
			Event:      record.EventMemorySurfaced,
			Subject:    record.Subject{MemoryID: demoMemory1, Scope: scope1, ContentHash: hash1},
			Content:    &record.Content{Text: demoText1},
		}, record.ReasonReturnedBySearch, `{"score":0.91,"rank":1}`,
			idemKey(record.EventMemorySurfaced, record.ReasonReturnedBySearch, scope1, "", "demo-search-1#1", hash1)),

		// A scope enumeration sees it still present.
		observed(record.Record{
			ID:         "demo-kept-1",
			At:         demoBase.Add(20 * time.Minute),
			RecordedAt: demoBase.Add(31 * time.Minute),
			Event:      record.EventMemoryKept,
			Subject:    record.Subject{MemoryID: demoMemory1, Scope: scope1, ContentHash: hash1},
		}, record.ReasonStoredByMem0, `{"source":"get_all"}`,
			claimKey(record.EventMemoryKept, record.ReasonStoredByMem0, demoMemory1, hash1, "")),

		// The claim this whole fixture exists for: a RECONSTRUCTED claim that
		// the memory was kept because its content matched the earlier add. The
		// event it describes happened on 1 September; the claim was written a
		// month later, and `explain --memory` must make that gap legible.
		reconstructed(record.Record{
			ID:         "demo-kept-1#content",
			At:         demoBase.Add(20 * time.Minute),
			RecordedAt: demoBase.Add(30*24*time.Hour + 20*time.Minute),
			Event:      record.EventMemoryKept,
			Subject:    record.Subject{MemoryID: demoMemory1, Scope: scope1, ContentHash: hash1},
		}, record.ReasonKeptByContentMatch, []record.RecordID{"demo-add-1"}, "kept_by_content_match", "1", 0.9,
			claimKey(record.EventMemoryKept, record.ReasonKeptByContentMatch, demoMemory1, hash1, "1")),

		// The second memory: requested...
		observed(record.Record{
			ID:         "demo-add-2",
			At:         demoBase.Add(time.Hour),
			RecordedAt: demoBase.Add(time.Hour + 2*time.Second),
			Event:      record.EventAddRequested,
			Subject:    record.Subject{MemoryID: demoMemory2, Scope: scope1, ContentHash: hash2},
			Content:    &record.Content{Text: demoText2},
		}, record.ReasonAddAcknowledged, `{"event_id":"demo-event-2","status":"PENDING"}`,
			idemKey(record.EventAddRequested, record.ReasonAddAcknowledged, scope1, "", "demo-add-2", hash2)),

		// ...then dropped, first as an inference a covering search rests on...
		reconstructed(record.Record{
			ID:         "demo-drop-2",
			At:         demoBase.Add(2 * time.Hour),
			RecordedAt: demoBase.Add(2*time.Hour + 5*time.Minute),
			Event:      record.EventMemoryDropped,
			Subject:    record.Subject{MemoryID: demoMemory2, Scope: scope1, ContentHash: hash2},
		}, record.ReasonAbsentFromSearch, []record.RecordID{"demo-add-2"}, "absent_from_search", "1", 0.7,
			claimKey(record.EventMemoryDropped, record.ReasonAbsentFromSearch, demoMemory2, hash2, "1")),

		// ...and then as an opacity marker: Mem0 removed it and said nothing.
		internalReason(record.Record{
			ID:         "demo-drop-2#internal",
			At:         demoBase.Add(3 * time.Hour),
			RecordedAt: demoBase.Add(3*time.Hour + 5*time.Minute),
			Event:      record.EventMemoryDropped,
			Subject:    record.Subject{MemoryID: demoMemory2, Scope: scope1, ContentHash: hash2},
		}, record.ReasonRemovedByMem0, "Mem0's history shows a DELETE for this memory and gives no reason",
			claimKey(record.EventMemoryDropped, record.ReasonRemovedByMem0, demoMemory2, hash2, "1")),
	}
}

// observed attaches an Observed reason built from a Mem0 response payload to
// rec. A failure here is a programming error in the fixtures, not an input
// error, so it is reported like every other failure: the fixture cannot be
// built, and the program exits non-zero rather than writing a half-ledger.
func observed(rec record.Record, kind record.ReasonKind, payload string, key record.IdemKey) record.Record {
	ev, err := record.NewObservedEvidence(record.SourceMem0Response, []byte(payload))
	if err != nil {
		fail("building observed evidence for %s: %v", rec.ID, err)
	}
	reason, err := record.NewObservedReason(kind, ev)
	if err != nil {
		fail("building observed reason for %s: %v", rec.ID, err)
	}
	rec.Reason = reason
	rec.IdempotencyKey = key
	return rec
}

// reconstructed attaches a Reconstructed reason -- a claim resting on a named
// basis, rule and rule version -- to rec.
func reconstructed(rec record.Record, kind record.ReasonKind, basis []record.RecordID, rule, ruleVersion string, confidence float64, key record.IdemKey) record.Record {
	ev, err := record.NewReconstructedEvidence(basis, rule, ruleVersion, confidence)
	if err != nil {
		fail("building reconstructed evidence for %s: %v", rec.ID, err)
	}
	reason, err := record.NewReconstructedReason(kind, ev)
	if err != nil {
		fail("building reconstructed reason for %s: %v", rec.ID, err)
	}
	rec.Reason = reason
	rec.IdempotencyKey = key
	return rec
}

// internal attaches an Internal reason -- an opacity marker carrying no
// observable claim -- to rec.
func internalReason(rec record.Record, kind record.ReasonKind, note string, key record.IdemKey) record.Record {
	n, err := record.NewInternalNote(note)
	if err != nil {
		fail("building internal note for %s: %v", rec.ID, err)
	}
	reason, err := record.NewInternalReason(kind, n)
	if err != nil {
		fail("building internal reason for %s: %v", rec.ID, err)
	}
	rec.Reason = reason
	rec.IdempotencyKey = key
	return rec
}

// idemKey derives the request path's idempotency key exactly as the
// interceptor's Observer does (record.DeriveIdemKey, over the event kind, the
// reason kind, the scope and the correlation or event id). The ledger never
// re-derives the key -- it only requires determinism -- but deriving it the
// real way is what makes the fixture behave like a real record on a re-run.
func idemKey(kind record.EventType, reasonKind record.ReasonKind, scope record.Scope, eventID, correlationID string, digest record.Hash) record.IdemKey {
	key, err := record.DeriveIdemKey(kind, reasonKind, scope, eventID, correlationID, digest)
	if err != nil {
		fail("deriving idempotency key for %s: %v", correlationID, err)
	}
	return key
}

// claimKey derives a derived claim's idempotency key exactly as
// internal/reconcile does (record.DeriveClaimIdemKey, over the memory id and
// the hex content digest). ruleVersion is empty for a claim no rule justified.
func claimKey(kind record.EventType, reasonKind record.ReasonKind, memoryID string, contentHash record.Hash, ruleVersion string) record.IdemKey {
	key, err := record.DeriveClaimIdemKey(kind, reasonKind, memoryID, hex.EncodeToString(contentHash[:]), ruleVersion)
	if err != nil {
		fail("deriving claim key for %s: %v", memoryID, err)
	}
	return key
}
